# apiKey: injected from CI/CD pipe
# database.connectionString: injected from CI/CD pipe

app:
  admin:
    cookieAttributes: "=$; Secure; HttpOnly; Domain=gattoslab.dev; SameSite=Strict; Max-Age=86400; Path=/admin;"
  cors:
    configuration: "https://gattoslab.dev,https://www.gattoslab.dev"
  security:
    enabled: true
security:
  require-ssl: true
server:
  port: 443
  ssl:
    key-store: "/etc/letsencrypt/live/gattoslab.dev-0001/keystore.p12"
    keyStoreType: "PKCS12"
    keyAlias: "tomcat"
