app:
  admin:
    apiKey: "test"
    cookieAttributes: "=$; Max-Age=86400; Path=/admin;"
  cors:
    configuration: "http://localhost:8080"
  database:
    connectionString: "mongodb://localhost:27017/GattosLabMongoDB"
  security:
    enabled: false
server:
  port: 8080
